/* 
 * surgipal_master
 *
 * API generated with [PHP-CRUD-API](https://github.com/mevdschee/php-crud-api)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Years_in_practiceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class Years_in_practiceApiTests
    {
        private Years_in_practiceApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new Years_in_practiceApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Years_in_practiceApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' Years_in_practiceApi
            //Assert.IsInstanceOfType(typeof(Years_in_practiceApi), instance, "instance is a Years_in_practiceApi");
        }

        
        /// <summary>
        /// Test YearsInPracticeGet
        /// </summary>
        [Test]
        public void YearsInPracticeGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string exclude = null;
            //string include = null;
            //string order = null;
            //string page = null;
            //bool? transform = null;
            //string columns = null;
            //List<string> filter = null;
            //string satisfy = null;
            //var response = instance.YearsInPracticeGet(exclude, include, order, page, transform, columns, filter, satisfy);
            //Assert.IsInstanceOf<List<InlineResponse20039>> (response, "response is List<InlineResponse20039>");
        }
        
        /// <summary>
        /// Test YearsInPracticeIdDelete
        /// </summary>
        [Test]
        public void YearsInPracticeIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.YearsInPracticeIdDelete(id);
            //Assert.IsInstanceOf<int?> (response, "response is int?");
        }
        
        /// <summary>
        /// Test YearsInPracticeIdGet
        /// </summary>
        [Test]
        public void YearsInPracticeIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.YearsInPracticeIdGet(id);
            //Assert.IsInstanceOf<InlineResponse20039> (response, "response is InlineResponse20039");
        }
        
        /// <summary>
        /// Test YearsInPracticeIdPatch
        /// </summary>
        [Test]
        public void YearsInPracticeIdPatchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //Item119 item = null;
            //var response = instance.YearsInPracticeIdPatch(id, item);
            //Assert.IsInstanceOf<int?> (response, "response is int?");
        }
        
        /// <summary>
        /// Test YearsInPracticeIdPut
        /// </summary>
        [Test]
        public void YearsInPracticeIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //Item118 item = null;
            //var response = instance.YearsInPracticeIdPut(id, item);
            //Assert.IsInstanceOf<int?> (response, "response is int?");
        }
        
        /// <summary>
        /// Test YearsInPracticePost
        /// </summary>
        [Test]
        public void YearsInPracticePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Item117 item = null;
            //var response = instance.YearsInPracticePost(item);
            //Assert.IsInstanceOf<int?> (response, "response is int?");
        }
        
    }

}
