/* 
 * surgipal_master
 *
 * API generated with [PHP-CRUD-API](https://github.com/mevdschee/php-crud-api)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20031
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse20031Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20031
        //private InlineResponse20031 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20031
            //instance = new InlineResponse20031();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20031
        /// </summary>
        [Test]
        public void InlineResponse20031InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse20031
            //Assert.IsInstanceOfType<InlineResponse20031> (instance, "variable 'instance' is a InlineResponse20031");
        }

        /// <summary>
        /// Test the property 'SurgeryId'
        /// </summary>
        [Test]
        public void SurgeryIdTest()
        {
            // TODO unit test for the property 'SurgeryId'
        }
        /// <summary>
        /// Test the property 'Patient'
        /// </summary>
        [Test]
        public void PatientTest()
        {
            // TODO unit test for the property 'Patient'
        }
        /// <summary>
        /// Test the property 'Term'
        /// </summary>
        [Test]
        public void TermTest()
        {
            // TODO unit test for the property 'Term'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'Reschedules'
        /// </summary>
        [Test]
        public void ReschedulesTest()
        {
            // TODO unit test for the property 'Reschedules'
        }
        /// <summary>
        /// Test the property 'Cancelled'
        /// </summary>
        [Test]
        public void CancelledTest()
        {
            // TODO unit test for the property 'Cancelled'
        }
        /// <summary>
        /// Test the property 'Completed'
        /// </summary>
        [Test]
        public void CompletedTest()
        {
            // TODO unit test for the property 'Completed'
        }
        /// <summary>
        /// Test the property 'Speciality'
        /// </summary>
        [Test]
        public void SpecialityTest()
        {
            // TODO unit test for the property 'Speciality'
        }
        /// <summary>
        /// Test the property 'CardId'
        /// </summary>
        [Test]
        public void CardIdTest()
        {
            // TODO unit test for the property 'CardId'
        }
        /// <summary>
        /// Test the property 'PreferenceCardName'
        /// </summary>
        [Test]
        public void PreferenceCardNameTest()
        {
            // TODO unit test for the property 'PreferenceCardName'
        }
        /// <summary>
        /// Test the property 'Initials'
        /// </summary>
        [Test]
        public void InitialsTest()
        {
            // TODO unit test for the property 'Initials'
        }
        /// <summary>
        /// Test the property 'SurgeryTime'
        /// </summary>
        [Test]
        public void SurgeryTimeTest()
        {
            // TODO unit test for the property 'SurgeryTime'
        }
        /// <summary>
        /// Test the property 'AdmissionStatus'
        /// </summary>
        [Test]
        public void AdmissionStatusTest()
        {
            // TODO unit test for the property 'AdmissionStatus'
        }
        /// <summary>
        /// Test the property 'Cpt'
        /// </summary>
        [Test]
        public void CptTest()
        {
            // TODO unit test for the property 'Cpt'
        }
        /// <summary>
        /// Test the property 'DiagnosisCode'
        /// </summary>
        [Test]
        public void DiagnosisCodeTest()
        {
            // TODO unit test for the property 'DiagnosisCode'
        }
        /// <summary>
        /// Test the property 'SurgerySnapshot'
        /// </summary>
        [Test]
        public void SurgerySnapshotTest()
        {
            // TODO unit test for the property 'SurgerySnapshot'
        }
        /// <summary>
        /// Test the property 'HospitalId'
        /// </summary>
        [Test]
        public void HospitalIdTest()
        {
            // TODO unit test for the property 'HospitalId'
        }
        /// <summary>
        /// Test the property 'HospitalEmail'
        /// </summary>
        [Test]
        public void HospitalEmailTest()
        {
            // TODO unit test for the property 'HospitalEmail'
        }
        /// <summary>
        /// Test the property 'Hospital'
        /// </summary>
        [Test]
        public void HospitalTest()
        {
            // TODO unit test for the property 'Hospital'
        }
        /// <summary>
        /// Test the property 'DoctorFosId'
        /// </summary>
        [Test]
        public void DoctorFosIdTest()
        {
            // TODO unit test for the property 'DoctorFosId'
        }
        /// <summary>
        /// Test the property 'DoctorEmail'
        /// </summary>
        [Test]
        public void DoctorEmailTest()
        {
            // TODO unit test for the property 'DoctorEmail'
        }
        /// <summary>
        /// Test the property 'DoctorDataId'
        /// </summary>
        [Test]
        public void DoctorDataIdTest()
        {
            // TODO unit test for the property 'DoctorDataId'
        }
        /// <summary>
        /// Test the property 'DoctorImage'
        /// </summary>
        [Test]
        public void DoctorImageTest()
        {
            // TODO unit test for the property 'DoctorImage'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'CoordinatorName'
        /// </summary>
        [Test]
        public void CoordinatorNameTest()
        {
            // TODO unit test for the property 'CoordinatorName'
        }
        /// <summary>
        /// Test the property 'CoordinatorPhone'
        /// </summary>
        [Test]
        public void CoordinatorPhoneTest()
        {
            // TODO unit test for the property 'CoordinatorPhone'
        }
        /// <summary>
        /// Test the property 'CoordinatorEmail'
        /// </summary>
        [Test]
        public void CoordinatorEmailTest()
        {
            // TODO unit test for the property 'CoordinatorEmail'
        }
        /// <summary>
        /// Test the property 'OfficePhone'
        /// </summary>
        [Test]
        public void OfficePhoneTest()
        {
            // TODO unit test for the property 'OfficePhone'
        }
        /// <summary>
        /// Test the property 'Pager'
        /// </summary>
        [Test]
        public void PagerTest()
        {
            // TODO unit test for the property 'Pager'
        }
        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Test]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'BillingCoordinatorName'
        /// </summary>
        [Test]
        public void BillingCoordinatorNameTest()
        {
            // TODO unit test for the property 'BillingCoordinatorName'
        }
        /// <summary>
        /// Test the property 'BillingCoordinatorPhone'
        /// </summary>
        [Test]
        public void BillingCoordinatorPhoneTest()
        {
            // TODO unit test for the property 'BillingCoordinatorPhone'
        }
        /// <summary>
        /// Test the property 'BillingCoordinatorEmail'
        /// </summary>
        [Test]
        public void BillingCoordinatorEmailTest()
        {
            // TODO unit test for the property 'BillingCoordinatorEmail'
        }
        /// <summary>
        /// Test the property 'ManagerName'
        /// </summary>
        [Test]
        public void ManagerNameTest()
        {
            // TODO unit test for the property 'ManagerName'
        }
        /// <summary>
        /// Test the property 'ManagerPhone'
        /// </summary>
        [Test]
        public void ManagerPhoneTest()
        {
            // TODO unit test for the property 'ManagerPhone'
        }
        /// <summary>
        /// Test the property 'ManagerEmail'
        /// </summary>
        [Test]
        public void ManagerEmailTest()
        {
            // TODO unit test for the property 'ManagerEmail'
        }

    }

}
